spring:
  #编码过滤器配置
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  messages:
    encoding: UTF-8
  #数据源配置
  datasource:
    username: root
    password: password
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springbootdb?useUnicode=true&characterEncoding=utf8
server:
  port: 9090

## Mybatis 配置
mybatis:
  typeAliasesPackage: com.hand.demo.domain
  mapperLocations: classpath:mapper/*.xml

## 配置日志
logging:
  file: log/booksystem-moon.log
  level:
    com:
      hand:
        demo: debug
    org:
      springframework:
        web: info

## 查看自动配置清单
#debug: true

## 开启全部监控端点权限
endpoints:
  sensitive: false

