spring:
  #编码过滤器配置
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  messages:
    encoding: UTF-8
  #数据源配置
  datasource:
#    username: root
    username: chenbindb%chenbin
#    password: password
#    password: 123456
    password: wsxdr2345!
    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/springbootdb?useUnicode=true&characterEncoding=utf8
#    url: jdbc:mysql://192.168.99.100:3306/sakila?useUnicode=true&characterEncoding=utf8
    url: jdbc:mysql://chenbindb.mysqldb.chinacloudapi.cn:3306/springbootdb?useUnicode=true&characterEncoding=utf8
server:
  port: 9090

## Mybatis 配置
mybatis:
  typeAliasesPackage: com.hand.demo.domain
  mapperLocations: classpath:mapper/*.xml

## 配置日志
logging:
  file: log/BookSystem-01.log
  level:
    com:
      hand:
        demo: debug
    org:
      springframework:
        web: info